# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huskago/Documents/projects/BrainZip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huskago/Documents/projects/BrainZip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huskago/Documents/projects/BrainZip/CMakeFiles /home/huskago/Documents/projects/BrainZip//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huskago/Documents/projects/BrainZip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named brainzip

# Build rule for target.
brainzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 brainzip
.PHONY : brainzip

# fast build rule for target.
brainzip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/build
.PHONY : brainzip/fast

brainfuck.o: brainfuck.c.o
.PHONY : brainfuck.o

# target to build an object file
brainfuck.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/brainfuck.c.o
.PHONY : brainfuck.c.o

brainfuck.i: brainfuck.c.i
.PHONY : brainfuck.i

# target to preprocess a source file
brainfuck.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/brainfuck.c.i
.PHONY : brainfuck.c.i

brainfuck.s: brainfuck.c.s
.PHONY : brainfuck.s

# target to generate assembly for a file
brainfuck.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/brainfuck.c.s
.PHONY : brainfuck.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/main.c.s
.PHONY : main.c.s

zip.o: zip.c.o
.PHONY : zip.o

# target to build an object file
zip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/zip.c.o
.PHONY : zip.c.o

zip.i: zip.c.i
.PHONY : zip.i

# target to preprocess a source file
zip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/zip.c.i
.PHONY : zip.c.i

zip.s: zip.c.s
.PHONY : zip.s

# target to generate assembly for a file
zip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brainzip.dir/build.make CMakeFiles/brainzip.dir/zip.c.s
.PHONY : zip.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... brainzip"
	@echo "... brainfuck.o"
	@echo "... brainfuck.i"
	@echo "... brainfuck.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... zip.o"
	@echo "... zip.i"
	@echo "... zip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

